.TH "SLAM/Model/RobotState.cs" 3 "Thu Apr 24 2014" "SLAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLAM/Model/RobotState.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBSLAM\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "package \fBSLAM\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSLAM\&.RobotState\fP { \fBSLAM\&.RobotState\&.MovingForward\fP, \fBSLAM\&.RobotState\&.MovingBackward\fP, \fBSLAM\&.RobotState\&.RotatingLeft\fP, \fBSLAM\&.RobotState\&.RotatingRight\fP, \fBSLAM\&.RobotState\&.Halted\fP, \fBSLAM\&.RobotState\&.Scanning\fP }"
.br
.RI "\fIRobot state\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SLAM from the source code\&.
