.TH "SLAM/Model/Robot.cs" 3 "Thu Apr 24 2014" "SLAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLAM/Model/Robot.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSLAM\&.Robot\fP"
.br
.RI "\fIContains the exploration robot model as part of the Model-View-Controller (MVC) design pattern\&. This class does not contain any view specific code instead it acts as a state model for the robot recording its current x and y position, rotation, and state\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBSLAM\fP"
.br
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "package \fBSLAM\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SLAM from the source code\&.
