.TH "SLAM.MapView" 3 "Thu Apr 24 2014" "SLAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLAM.MapView \- 
.PP
Map view\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits DrawingArea\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapView\fP (\fBSlamMap\fP mapModel, \fBEkfSlam\fP SlamInstance)"
.br
.RI "\fIInitializes a new instance of the \fBSLAM\&.MapView\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSlamMap\fP \fBMapModel\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the map\&. \fP"
.ti -1c
.RI "\fBRobotView\fP \fBRobotView\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the robot view\&. \fP"
.ti -1c
.RI "int \fBViewWidth\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the width of the view\&. \fP"
.ti -1c
.RI "int \fBViewHeight\fP\fC [get, set]\fP"
.br
.RI "\fIGets or sets the height of the view\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Map view\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "SLAM\&.MapView\&.MapView (\fBSlamMap\fPmapModel, \fBEkfSlam\fPSlamInstance)"

.PP
Initializes a new instance of the \fBSLAM\&.MapView\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImapModel\fP Map model\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBSlamMap\fP SLAM\&.MapView\&.MapModel\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the map\&. The map\&.
.SS "\fBRobotView\fP SLAM\&.MapView\&.RobotView\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the robot view\&. The robot view\&.
.SS "int SLAM\&.MapView\&.ViewHeight\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the height of the view\&. The height of the view\&.
.SS "int SLAM\&.MapView\&.ViewWidth\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the width of the view\&. The width of the view\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SLAM from the source code\&.
