.TH "SLAM.Landmark" 3 "Thu Apr 24 2014" "SLAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLAM.Landmark \- 
.PP
\fBLandmark\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLandmark\fP ()"
.br
.RI "\fIInitializes a new instance of the \fBSLAM\&.Landmark\fP class\&. \fP"
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "\fIReturns a System\&.String that represents the current \fBSLAM\&.Landmark\fP\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double[] \fBpos\fP"
.br
.ti -1c
.RI "double[] \fBx1y1\fP"
.br
.ti -1c
.RI "double[] \fBx2y2\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBlife\fP"
.br
.ti -1c
.RI "int \fBtotalTimesObserved\fP"
.br
.ti -1c
.RI "double \fBrange\fP"
.br
.ti -1c
.RI "double \fBbearing\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "double \fBrangeError\fP"
.br
.ti -1c
.RI "double \fBbearingError\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLandmark\fP\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "SLAM\&.Landmark\&.Landmark ()"

.PP
Initializes a new instance of the \fBSLAM\&.Landmark\fP class\&. 
.SH "Member Function Documentation"
.PP 
.SS "override string SLAM\&.Landmark\&.ToString ()"

.PP
Returns a System\&.String that represents the current \fBSLAM\&.Landmark\fP\&. 
.PP
\fBReturns:\fP
.RS 4
A System\&.String that represents the current \fBSLAM\&.Landmark\fP\&.
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "double SLAM\&.Landmark\&.a"

.SS "double SLAM\&.Landmark\&.b"

.SS "double SLAM\&.Landmark\&.bearing"

.SS "double SLAM\&.Landmark\&.bearingError"

.SS "int SLAM\&.Landmark\&.id"

.SS "int SLAM\&.Landmark\&.life"

.SS "double [] SLAM\&.Landmark\&.pos"

.SS "double SLAM\&.Landmark\&.range"

.SS "double SLAM\&.Landmark\&.rangeError"

.SS "int SLAM\&.Landmark\&.totalTimesObserved"

.SS "double [] SLAM\&.Landmark\&.x1y1"

.SS "double [] SLAM\&.Landmark\&.x2y2"


.SH "Author"
.PP 
Generated automatically by Doxygen for SLAM from the source code\&.
