.TH "SLAM.MapWindow" 3 "Thu Apr 24 2014" "SLAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLAM.MapWindow \- 
.PP
Map window\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapWindow\fP (\fBMapView\fP mapView)"
.br
.RI "\fIInitializes a new instance of the \fBSLAM\&.MapWindow\fP class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Map window\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "SLAM\&.MapWindow\&.MapWindow (\fBMapView\fPmapView)"

.PP
Initializes a new instance of the \fBSLAM\&.MapWindow\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImapView\fP Map view contained in this window\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SLAM from the source code\&.
