.TH "SLAM.MapUpdateEventArgs" 3 "Thu Apr 24 2014" "SLAM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLAM.MapUpdateEventArgs \- 
.PP
An event to handle any updates to the map\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapUpdateEventArgs\fP (\fBSlamMap\fP updatedMap)"
.br
.RI "\fIInitializes a new instance of the \fBSLAM\&.MapUpdateEventArgs\fP class\&. \fP"
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSlamMap\fP \fBMap\fP\fC [get]\fP"
.br
.RI "\fIGets the map\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An event to handle any updates to the map\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "SLAM\&.MapUpdateEventArgs\&.MapUpdateEventArgs (\fBSlamMap\fPupdatedMap)"

.PP
Initializes a new instance of the \fBSLAM\&.MapUpdateEventArgs\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIupdatedMap\fP Updated map\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBSlamMap\fP SLAM\&.MapUpdateEventArgs\&.Map\fC [get]\fP"

.PP
Gets the map\&. The map\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SLAM from the source code\&.
